language: go

go:
  - "1.13"
services:
  - docker
env:
  - OPERATOR_VERSION=v0.17.0
install:
  - curl -o operator-sdk -L https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
  - chmod +x operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu && sudo mkdir -p /usr/local/bin/ && sudo cp operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu /usr/local/bin/operator-sdk && rm operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
script:
  - operator-sdk build devcsrj/gravitee-operator:${TRAVIS_TAG:-latest}
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  on:
    tags: true
  script: docker push devcsrj/gravitee-operator
